// <auto-generated />
using System;
using FirePlatform.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirePlatform.Models.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191121205154_Add-column-MainTemplate-UserTemplatesTable")]
    partial class AddcolumnMainTemplateUserTemplatesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FirePlatform.Models.Models.TemplateModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("FirePlatform.Models.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FirePlatform.Models.Models.UserForm", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("FormId");

                    b.Property<int>("Id");

                    b.HasKey("UserId", "FormId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("UserForm");
                });

            modelBuilder.Entity("FirePlatform.Models.Models.UserTemplates", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Data");

                    b.Property<int>("Id")
                        .HasColumnName("UserTemplates_Id");

                    b.Property<string>("MainName");

                    b.Property<string>("Name");

                    b.HasKey("UserId");

                    b.HasAlternateKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FirePlatform.Models.Models.UserForm", b =>
                {
                    b.HasOne("FirePlatform.Models.Models.TemplateModel", "Form")
                        .WithMany("UserForms")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FirePlatform.Models.Models.User", "User")
                        .WithMany("UserForms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FirePlatform.Models.Models.UserTemplates", b =>
                {
                    b.HasOne("FirePlatform.Models.Models.User", "User")
                        .WithMany("UserTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
